drop table USER_DETAILS;
drop table USER_TABLE;
drop table PERSISTENT_LOGINS;
DROP SEQUENCE USER_TABLE_SEQ;
DROP SEQUENCE USER_DETAILS_SEQ;

CREATE TABLE USER_TABLE
(
  	ID       NUMBER(*,0) NOT NULL ENABLE PRIMARY KEY,
    EMAIL    VARCHAR2(45 BYTE) UNIQUE,
    PASSWORD VARCHAR2(45 BYTE) DEFAULT NULL
);

CREATE TABLE USER_DETAILS
(
    ID            NUMBER(*,0) NOT NULL ENABLE PRIMARY KEY,
    USER_TABLE_ID NUMBER(*,0) NOT NULL ENABLE,
    FIRST_NAME    VARCHAR2(45 BYTE) DEFAULT NULL,
    LAST_NAME     VARCHAR2(45 BYTE) DEFAULT NULL,
    BIRTHDAY DATE DEFAULT NULL,
    GENDER CHAR(1 BYTE) DEFAULT NULL,
    CONSTRAINT FK_USER_TABLE FOREIGN KEY (USER_TABLE_ID) REFERENCES USER_TABLE (ID) ENABLE
);

CREATE TABLE PERSISTENT_LOGINS
(
    USERNAME VARCHAR2(64 BYTE) NOT NULL ENABLE PRIMARY KEY,
    SERIES   VARCHAR2(64 BYTE),
    TOKEN    VARCHAR2(64 BYTE) NOT NULL ENABLE,
    LAST_USED TIMESTAMP (6) NOT NULL ENABLE
);

CREATE SEQUENCE USER_TABLE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 227 CACHE 20 NOORDER NOCYCLE ;

CREATE SEQUENCE USER_DETAILS_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 222 CACHE 20 NOORDER NOCYCLE ;
  
INSERT INTO USER_TABLE VALUES (USER_TABLE_SEQ.NEXTVAL, 'cheenu78@gmail.com', 'abcd123');

INSERT INTO USER_TABLE VALUES (USER_TABLE_SEQ.NEXTVAL, 'gireesh.nemath@gmail.com', 'abcd123');

INSERT INTO USER_DETAILS VALUES 
(USER_DETAILS_SEQ.NEXTVAL, 
		(SELECT ID FROM USER_TABLE 
			WHERE EMAIL = 'cheenu78@gmail.com'
		), 
		'Srinivasa Gopalan', 'Parthasarathi', sysdate, 1);

INSERT INTO USER_DETAILS VALUES 
(USER_DETAILS_SEQ.NEXTVAL, 
		(SELECT ID FROM USER_TABLE
			WHERE EMAIL = 'gireesh.nemath@gmail.com'
		), 
		'Gireesh', 'Nemath', sysdate, 1);
